### PR TITLE
For #83: Errors table.

### PR DESCRIPTION
**Pull request by paulodamaso**
For #83: Created errors table specs on `errors.json` file.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#89](https://github.com/yegor256/wring/issues/89) is now in scope, role is `REV`

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status  ([here](https://github.com/yegor256/wring/issues/89#issuecomment-455262807))

@paulodamaso This is what I know about this job in [C7FCB1EQN](https://www.0crat.com/p/C7FCB1EQN), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#89](https://github.com/yegor256/wring/issues/89) is [in scope](http://www.zerocracy.com/policy.html#14) for 22days
  * The role is `REV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7FCB1EQN?q=%7Bjob%3A%27gh%3Ayegor256%2Fwring%2389%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@carlosmiranda please take a look at this

**Comment by paulodamaso** [comment]
@carlosmiranda ping

**Comment by carlosmiranda** [comment]
@paulodamaso make sure to remove the puzzle in #83 as well (it's still there, since Yegor closed it manually)

**Comment by paulodamaso** [comment]
@carlosmiranda done, please take a look

**Comment by carlosmiranda** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/wring#89` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#89](https://github.com/yegor256/wring/issues/89) is now out of scope

**Pull request merged**
